### ISSUE TITLE
Setup Guide? (Question)

### ISSUE THREAD

**Issue by homebrewhops** [skyride/avrse-auth#5]
Aside from sudo pip install -r requirements.txt and modifying settings.py are there any specific instructions for getting this up and running? Looking to put this behind apache with mod_wsgi unless there is a better way.

Thanks!

**Comment by skyride** [comment]
Hey man,

I'm slowly adding stuff and changing thing that make it easier so I've not
written one yet because it'd change slightly almost every week. Tl;dr you
need mysql or postgres server, redis, memcache, something to serve wsgi
like you said, and virtualenv to wrap it in.

Once you've done that you just need go to avrseauth/, copy the example
local settings, fill it in, do the same for eveauth/config.yaml (discord
token), then it should be good. discord.sh to run the discord bot, celery
for the background jobs and wsgi for the site. You also need to run these
commands on manage.py

updatescopes
fetchsde
updatesde

the latter 2 should be run any time theres a new evepatch when fuzzworks
gets updated.

I'll write one eventually its still just a little early to write solid
instructions.

**Comment by skyride** [comment]
Guide created now

https://github.com/skyride/avrse-auth/blob/master/docs/installation.md
