### ISSUE TITLE
ESI client question

### ISSUE THREAD

**Issue by spemmons** [skyride/avrse-auth#6]
local_settings calls for 2 different ESI application client IDs

i keep getting the following error with my client ID/secret

```
{"error":"invalid_scope","error_description":"The requested scopes either don't exist, or are not valid for this client"}
```

i thought the SOCIAL_AUTH_CHARACTER_AUTH_SCOPE scopes were needed, but then i realized that this is for the "character" client not the "login" client

i can't seem to find where the "login" client defines its needed scopes that ESI is complaining aren't available

can you point me in the right direction?

thanks!

**Comment by spemmons** [comment]
arg! nevermind -- it's `publicData`

**Comment by skyride** [comment]
No worries man hope you get good use out of it :)

Generally you can just grant all scopes to an application in the developers site application because the token it generates will be only be valid for the scopes it requests. The list at developers.eveonline.com is only the list of what scopes the application is allowed to _ask_ for, not what it actually gets.

https://github.com/skyride/avrse-auth/blob/master/avrseauth/settings.py#L132-L158
